### ISSUE TITLE
Lenovo Ideapad 710S not working for the plus model?

### ISSUE THREAD

**Issue by mapleloops** [hirschmann/nbfc#276] opened 2017-06-21 19:33 UTC
Hi,
thanks for providing the fan control application as well as the different configurations. I have a Lenovo Ideapad 710s plus and thought that the already available "Lenovo Ideapad 710S.xml" config will work but unfortunately, as shown in the screenshot provided, the current fan speed of around 140% does never change (no matter if it gets hotter or not). Furthermore, when I open programs like Photoshop the temperature easily goes up to 60-65 degrees and the fan starts to kick in pretty loud over 45 degrees. This shouldn't happen right?

It would be amazing if anyone could help me with that, since I do not want to do it with wrong settings.
Many thanks in advance

![capture](https://user-images.githubusercontent.com/11430281/27402918-baaf4a0c-56c8-11e7-853d-dcb2c2fe5490.PNG)

**Comment by hirschmann** [comment] 2017-06-21 23:37
Duplicate of #208

**Closed by hirschmann** 2017-06-21 23:37 UTC
