### ISSUE TITLE
Build FAILED.

### ISSUE THREAD

**Issue by iPadGuy** [hirschmann/nbfc#189] opened 2017-02-16 17:01 UTC
I've got build errors on Ubuntu 16.04 with mono 4.2.1.  The compiler summary is shown below.  Any suggestions?

Thanks!

===========================================================================
Build FAILED.

Warnings:

/opt/nbfc-1.5.0/Windows/Setup/NbfcSetup/NbfcSetup.wixproj:  warning : **Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring**.
/opt/nbfc-1.5.0/Windows/Setup/NbfcBootstrapper/NbfcBootstrapper.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/opt/nbfc-1.5.0/Windows/Setup/DriverSetupWixAction/DriverSetupWixAction.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.CA.targets, to import. Ignoring.

/opt/nbfc-1.5.0/NoteBookFanControl.sln (Build) ->
(Build target) ->
/opt/nbfc-1.5.0/Tests/StagWare.FanControl.Tests/StagWare.FanControl.Tests.csproj (default targets) ->

	/opt/nbfc-1.5.0/Tests/StagWare.FanControl.Tests/StagWare.FanControl.Tests.csproj:  warning : **Project has unknown ToolsVersion '14.0'. Using the default tools version '4.0' instead**.

Errors:

/opt/nbfc-1.5.0/NoteBookFanControl.sln (Build) ->
(Build target) ->
/opt/nbfc-1.5.0/Tests/StagWare.FanControl.Tests/StagWare.FanControl.Tests.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	**FanControlTests.cs(52,66): error CS8082: An argument to nameof operator cannot include sub-expression**

===========================================================================
.

**Comment by hirschmann** [comment] 2017-02-16 18:46
This issue has already been fixed. Check out the master branch.
Duplicate of #158

**Closed by hirschmann** 2017-02-16 18:46 UTC
