### ISSUE TITLE
build.sh: 10: build.sh: Syntax error: "}" unexpected

### ISSUE THREAD

**Issue by Koploseus** [hirschmann/nbfc#329] opened 2017-09-04 21:06 UTC
Hello!

I just download the nbfc project in my opt directory. I launch the build.sh file and i get this error : 

build.sh: 10: build.sh: Syntax error: "}" unexpected

when i open the file and that i launch : xbuild /t:Build /p:Configuration=ReleaseLinux NoteBookFanControl.sln

I get plenty for errors.

I am on Debian 9, can i have some help ? Thanks :)

**Comment by hirschmann** [comment] 2017-09-05 17:18
Duplicate of #324

**Closed by hirschmann** 2017-09-05 17:18 UTC
