### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by picarr** [hirschmann/nbfc#285] opened 2017-07-09 13:05 UTC
Hello ,

i cloned the git hub package nfbc and try to buld it and become 5 errors. Maybe someone has an idea to solve it. 

Build FAILED.

Warnings:

/home/ludi/nbfc/Windows/Setup/NbfcSetup/NbfcSetup.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/home/ludi/nbfc/Windows/Setup/NbfcBootstrapper/NbfcBootstrapper.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/home/ludi/nbfc/Windows/Setup/DriverSetupWixAction/DriverSetupWixAction.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.CA.targets, to import. Ignoring.

/home/ludi/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/home/ludi/nbfc/Core/StagWare.Configurations/StagWare.FanControl.Configurations.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.IO.Abstractions, Version=2.0.0.144, Culture=neutral, processorArchitecture=MSIL' not resolved

Errors:

/home/ludi/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/home/ludi/nbfc/Core/StagWare.Configurations/StagWare.FanControl.Configurations.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	ConfigManager.cs(4,17): error CS0234: The type or namespace name 'Abstractions' does not exist in the namespace 'System.IO' (are you missing an assembly reference?)
	FanControlConfigManager.cs(8,17): error CS0234: The type or namespace name 'Abstractions' does not exist in the namespace 'System.IO' (are you missing an assembly reference?)
	FanControlConfigManager.cs(52,91): error CS0246: The type or namespace name 'IFileSystem' could not be found (are you missing a using directive or an assembly reference?)
	ConfigManager.cs(29,17): error CS0246: The type or namespace name 'IFileSystem' could not be found (are you missing a using directive or an assembly reference?)
	ConfigManager.cs(69,81): error CS0246: The type or namespace name 'IFileSystem' could not be found (are you missing a using directive or an assembly reference?)

	 4 Warning(s)
	 5 Error(s)

Time Elapsed 00:00:03.6885650

**Comment by xjjiao** [comment] 2017-07-10 05:22
I had the exactly same errors.
I also tried to build the 1.5.0, and it was built successfully, but NO ReleaseLinux folder was generated.
OS: Ubuntu 16.04 LTS 64-bit.
Please help.

Thanks!

**Comment by hirschmann** [comment] 2017-07-10 17:39
Duplicate of issue #265

**Closed by hirschmann** 2017-07-10 17:39 UTC

**Comment by xjjiao** [comment] 2017-07-11 04:46
I think I installed the latest mono-complete, whose version is 5.0.1.1. But I still get the same error.

**Comment by xjjiao** [comment] 2017-07-11 06:19
Actually the answer to issue#236 fix my problem. 
i.e. to use the stable version (4.1.0) of nuget.exe
Thanks.

**Comment by picarr** [comment] 2017-07-11 06:44
Same over here i downloaded nuget.exe version 4.1.0 and it worked.

Thanks!!

**Comment by dr-monro** [comment] 2020-11-02 13:14
Met this problem when build with mono docker. Seems latest version of mono docker didn't contain wget. Solved by installing wget.
