### ISSUE TITLE
Lenovo Yoga 2 13 - battery problems

### ISSUE THREAD

**Issue by ado-kollarik** [hirschmann/nbfc#76] opened 2016-04-04 07:26 UTC
After installing the app on Lenovo Yoga 2 13 and selecting the closest profile, the app prevents the battery from charging, laptop recognises that power cord is plugged it, but is unable to charge the battery. After removing the app, charging works again.

**Comment by mathiasluethi** [comment] 2016-04-25 10:03
I have the same problem with my Lenovo Yoga 3 14.

**Comment by hirschmann** [comment] 2017-06-22 15:06
Duplicate of issue #10

**Closed by hirschmann** 2017-06-22 15:06 UTC
