### ISSUE TITLE
When build is execute nuget.exe is not found

### ISSUE THREAD

**Issue by TobiasKi** [hirschmann/nbfc#64] opened 2016-02-26 10:18 UTC
I am in Powershell console and execute Build.ps1. The error is that nuget.exe can not be found as part of a CmdLet, Function or script. But nuget.exe is in the directory from which I execute build.ps1 :(

**Comment by hirschmann** [comment] 2016-02-26 14:51
nuget.exe should be in the nbfc directory, otherwise it will not work.
From which location did you execute the script?

**Comment by Hornstrom** [comment] 2016-03-18 10:59
I'm also having trouble executing the build script. Navigated to C:\Users\horns\nbfc in powershell where the git command placed the files and did .\build.ps1 to run the script. There is a nuget.exe in that folder. Am I doing something wrong? At the top it says this:
nuget.exe : The term 'nuget.exe' is not recognized as the name of a cmdlet, function, script file, or operable program.

>  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At C:\Users\horns\nbfc\build.ps1:10 char:1
> + nuget.exe restore
> + ~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (nuget.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
And at the end it says this:

> Suggestion [3,General]: The command nuget.exe was not found, but does exist in the current location. Windows PowerShell
> does not load commands from the current location by default. If you trust this command, instead type: ".\nuget.exe". See
>  "get-help about_Command_Precedence" for more details.
There is something like 85 build errors while it tries to execute the script but I'm guessing thats because nuget dosen't execute correctly?

**Comment by hirschmann** [comment] 2016-03-22 22:47
Like the suggestion says, powershell does not load commands from the current location.
On my system powershell behaves differently (the build script works), so I couldn't reproduce your error.

Nevertheless, I fixed the build script, so it should work on your system: d94512ad560949c2444472b723a756585fe42f6a

Thanks for your bug report!

**Comment by TobiasKi** [comment] 2016-03-30 13:33
Thanks. With the latest fix in the script nuget.exe can be found. However, when I run the buildscript I get another issue now. It's saying that ".NETFramework,Version=v4.5,Profile=Mono" can not be found. There more details saying that Mono.Posix-Assembly can not be found as well. On my system .NET 4.0 is installed. When I download the package from the link given on your repository landing page, it's saying that I can not continue because it is included in my system already. 3.9.1208.0 on my system as well (seems to be the latest version).

**Comment by hirschmann** [comment] 2016-03-30 20:31
The issue is caused by a litte workaround I used to build the plugins for Linux on Windows (just to see if it works ;)).

Should be fixed now: 6db1df3ec7cf56615dbfbe64ba37c0e51148cce5

**Comment by TobiasKi** [comment] 2016-04-04 08:38
Yes, thank you. It is the fix!

**Closed** 2016-08-02 17:05 UTC
